### ISSUE TITLE
how to get RS to KB linkage?

### ISSUE THREAD

**Issue by SerenaChristmas** [RUCDM/KB4Rec#5]
In your paper, "With an ofine Freebase search API, , we retrieve KB entities with item titles as queries. " Cause the Freebase API has been shut down according to https://developers.google.com/freebase, could you please to tell me how to convert item id to entity id in KB. Would you do me a favor to make this process open source? Thank you very much~

**Comment by RichardHGL** [comment]
google knowledge graph api can provide retrieval result about item title, which include freeebase entities.
But as we find, it may be more efficient to directly match entity's object.name attribute with item title

**Comment by wei1826676931** [comment]
I have the same problem. The freebase interface has been closed. How do you match the name or attribute of an entity through the unique meaningless id in the triplet?
As far as I know, Google provides some freebase to wiki mappings, but only a very small part.
So what I am curious about is how to match the entity only by the meaningless id in the triples in freebase?
Finally, thank you very much for reading.

**Comment by RichardHGL** [comment]
Previously, we did try to access the search API for Freebase with google knowledge graph API. But a more convenient way is to conduct matching through "type.object.name" relation of entities (from the largest dump) to find name match.

**Comment by wei1826676931** [comment]
哦哦哦，是通过图一中的这个文件：所有的三元组数据。通过里面的type.object.name关系去找到名字，最后通过名字再去匹配对吗？
(图一)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Gaole He ***@***.***&gt;; 
发送时间: 2021年11月17日(星期三) 下午5:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [RUCDM/KB4Rec] how to get RS to KB linkage? (#5)





 
Previously, we did try to access the search API for Freebase with google knowledge graph API. But a more convenient way is to conduct matching through "type.object.name" relation of entities (from the largest dump) to find name match.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by RichardHGL** [comment]
Yes. You can follow the code we used in this repo to deal with dump file
